CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,

    CONSTRAINT uq_games_title UNIQUE (title)
);

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handle VARCHAR(255) NOT NULL,

    CONSTRAINT uq_app_users_handle UNIQUE (handle)
);

CREATE TABLE checkpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    label VARCHAR(255) NOT NULL,
    position INTEGER NOT NULL,

    CONSTRAINT ck_checkpoints_position_positive
        CHECK (position > 0),

    CONSTRAINT uq_checkpoints_game_position
        UNIQUE (game_id, position),

    CONSTRAINT uq_checkpoints_id_game
        UNIQUE (id, game_id),

    CONSTRAINT fk_checkpoints_game
        FOREIGN KEY (game_id)
        REFERENCES games (id)
);

CREATE TABLE user_game_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    checkpoint_id BIGINT NOT NULL,

    CONSTRAINT uq_user_game_progress_user_game
        UNIQUE (user_id, game_id),

    CONSTRAINT fk_user_game_progress_user
        FOREIGN KEY (user_id)
        REFERENCES app_users (id),

    CONSTRAINT fk_user_game_progress_game
        FOREIGN KEY (game_id)
        REFERENCES games (id),

    CONSTRAINT fk_user_game_progress_checkpoint_game
        FOREIGN KEY (game_id, checkpoint_id)
        REFERENCES checkpoints (game_id, id)
);

CREATE TABLE journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    checkpoint_id BIGINT NOT NULL,
    content VARCHAR(5000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_journal_entries_author
        FOREIGN KEY (author_id)
        REFERENCES app_users (id),

    CONSTRAINT fk_journal_entries_checkpoint
        FOREIGN KEY (checkpoint_id)
        REFERENCES checkpoints (id)
);