CREATE TABLE journal_entry_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content VARCHAR(5000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_journal_entry_replies_entry
        FOREIGN KEY (journal_entry_id)
        REFERENCES journal_entries (id),

    CONSTRAINT fk_journal_entry_replies_author
        FOREIGN KEY (author_id)
        REFERENCES app_users (id)
);

CREATE INDEX idx_journal_entry_replies_entry_created
    ON journal_entry_replies (journal_entry_id, created_at, id);