ALTER TABLE games
    ADD COLUMN rawg_game_id BIGINT,
    ADD COLUMN cover_image_url VARCHAR(1000),
    ADD COLUMN release_date DATE;

ALTER TABLE games
    ADD CONSTRAINT uq_games_rawg_game_id UNIQUE (rawg_game_id);

CREATE TABLE game_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rawg_game_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    release_date DATE,
    cover_image_url VARCHAR(1000),
    suggested_by_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reviewed_by_id BIGINT,
    reviewed_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uq_game_suggestions_rawg_game_id UNIQUE (rawg_game_id),
    CONSTRAINT ck_game_suggestions_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT fk_game_suggestions_suggested_by
        FOREIGN KEY (suggested_by_id)
        REFERENCES app_users (id),
    CONSTRAINT fk_game_suggestions_reviewed_by
        FOREIGN KEY (reviewed_by_id)
        REFERENCES app_users (id)
);

CREATE INDEX idx_game_suggestions_status_created
    ON game_suggestions (status, created_at, id);
