CREATE TABLE checkpoint_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    label VARCHAR(255) NOT NULL,
    position INTEGER NOT NULL,
    suggested_by_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reviewed_by_id BIGINT,
    reviewed_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT ck_checkpoint_suggestions_position CHECK (position > 0),
    CONSTRAINT ck_checkpoint_suggestions_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT fk_checkpoint_suggestions_game
        FOREIGN KEY (game_id)
        REFERENCES games (id),
    CONSTRAINT fk_checkpoint_suggestions_suggested_by
        FOREIGN KEY (suggested_by_id)
        REFERENCES app_users (id),
    CONSTRAINT fk_checkpoint_suggestions_reviewed_by
        FOREIGN KEY (reviewed_by_id)
        REFERENCES app_users (id)
);

CREATE UNIQUE INDEX uq_checkpoint_suggestions_pending_game_position
    ON checkpoint_suggestions (game_id, position)
    WHERE status = 'PENDING';

CREATE INDEX idx_checkpoint_suggestions_status_created
    ON checkpoint_suggestions (status, created_at, id);
