CREATE TABLE user_game_library (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT uq_user_game_library_user_game UNIQUE (user_id, game_id),
    CONSTRAINT ck_user_game_library_status
        CHECK (status IN ('WANT_TO_PLAY', 'PLAYING', 'COMPLETED')),
    CONSTRAINT fk_user_game_library_user
        FOREIGN KEY (user_id)
        REFERENCES app_users (id),
    CONSTRAINT fk_user_game_library_game
        FOREIGN KEY (game_id)
        REFERENCES games (id)
);

CREATE INDEX idx_user_game_library_user_status
    ON user_game_library (user_id, status, id);

CREATE INDEX idx_user_game_library_user_favorite
    ON user_game_library (user_id, favorite, id)
    WHERE favorite = TRUE;

INSERT INTO user_game_library (
    user_id,
    game_id,
    status,
    favorite,
    created_at,
    updated_at
)
SELECT
    progress.user_id,
    progress.game_id,
    'PLAYING',
    FALSE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM user_game_progress AS progress
ON CONFLICT (user_id, game_id) DO NOTHING;
