spring.application.name=umbral
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/umbral
spring.datasource.username=umbral
spring.datasource.password=umbral_local
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# Initial data
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
